In [18]:
# !pip install torch

In [19]:
import torch

t = torch.tensor([1., 3., 5., 7., 9., 4])
print(t)

tensor([1., 3., 5., 7., 9., 4.])


In [20]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([6])
torch.Size([6])


In [21]:
print(t[0], t[3], t[-1])
print(t[1:4], t[3:-1])
print(t[:3],t[4:])

tensor(1.) tensor(7.) tensor(4.)
tensor([3., 5., 7.]) tensor([7., 9.])
tensor([1., 3., 5.]) tensor([9., 4.])


In [22]:
t = torch.tensor([[1,3,5],
[7,9,11],
[2,4,6],
[8,10,12]])

print(t.dim())
print(t.shape)

2
torch.Size([4, 3])


In [23]:
print(t)
print()
print(t[0,0], t[3, -1])
print()
print(t[0], t[0, :])
print(t[0].shape)
print()
print(t[:, 2])
print(t[:, 2].shape)
print()
print(t[1:4, :2])

tensor([[ 1,  3,  5],
        [ 7,  9, 11],
        [ 2,  4,  6],
        [ 8, 10, 12]])

tensor(1) tensor(12)

tensor([1, 3, 5]) tensor([1, 3, 5])
torch.Size([3])

tensor([ 5, 11,  6, 12])
torch.Size([4])

tensor([[ 7,  9],
        [ 2,  4],
        [ 8, 10]])


In [ ]:
# empty : 공간 확보 목적 p30
t = torch.empty([3, 4])
print(t)
print(torch.empty_like(t))
print(torch.empty(t.shape))

# zeros : 입력 모양에 맞게 0으로 초기화된 텐서 생성
t = torch.zeros([3,2,2])
tl = torch.zeros_like(t)
print(t)
print(tl)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[3.2829e-27, 2.0179e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


In [ ]:
# ones
t = torch.ones([2,3,4])
tl = torch.ones_like(t)
print(t)
print(tl)

# full p 31

t = torch.full([1,2,4], 7)
tl = torch.full_like(t, 9)
print(t)
print(tl)

# random 
print(torch.rand([3,4])) # 0~1 범위에서 랜덤한 값으로 채움
print(torch.randn([2, 3]))  # random normal 로 평균 0, 분산 1인 표준정규분포 값으로 채움
print(torch.randint(0, 5, [2, 4]))  # 정수형 텐서를 반환하고 최소-최대값 범위의 균일 분포값으로 채움

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[7, 7, 7, 7],
         [7, 7, 7, 7]]])
tensor([[[9, 9, 9, 9],
         [9, 9, 9, 9]]])
tensor([[0.8080, 0.3192, 0.4789, 0.4615],
        [0.2269, 0.8686, 0.7431, 0.8194],
        [0.7212, 0.4207, 0.7648, 0.7951]])
tensor([[-0.1071, -2.1932, -0.1350],
        [-0.7949,  1.0020,  2.3503]])
tensor([[4, 4, 0, 0],
        [2, 4, 1, 4]])


In [32]:
# 자주 사용되는 연산  p34
t = torch.arange(12).reshape(3,2,2)
print(t.shape)
print(t)
print(t.sum())

print(t.sum(dim=0))
print(t[:, 0,0], t[:, 0,0].sum())
print(t[:, 0,1], t[:, 0,1].sum())
print(t[:, 1,0], t[:, 1,0].sum())
print(t[:, 1,1], t[:, 1,1].sum())


torch.Size([3, 2, 2])
tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])
tensor(66)
tensor([[12, 15],
        [18, 21]])
tensor([0, 4, 8]) tensor(12)
tensor([1, 5, 9]) tensor(15)
tensor([ 2,  6, 10]) tensor(18)
tensor([ 3,  7, 11]) tensor(21)


In [33]:
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[ 2,  4],
        [10, 12],
        [18, 20]])
tensor([[ 1,  5],
        [ 9, 13],
        [17, 21]])


In [38]:
t = torch.tensor([[[ 1,  2],
         [ 3,  4],
        [ 5,  6]],
         [[ 7,  8],
        [ 9,  10],
         [11, 12]]])

print(t.argmax())
print(t.flatten())
print(t.flatten().max(dim=0)[1])

tensor(11)
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor(11)
